read.delim('https://raw.githubusercontent.com/HackBio-Internship/public_datasets/main/R/datasets/epidemiology_dataset')
epidem<-read.delim('https://raw.githubusercontent.com/HackBio-Internship/public_datasets/main/R/datasets/epidemiology_dataset')
head(epidem)
barplot(c(mean(epidem$host_time_point), mean(epidem$clutches)), xlab ='epidem', xaxt ='n')
axis(side = 1, at=c(1,2), labels=c('host','clutches'))
hist(epidem$lifespan, na.rm = TRUE)
hist(epidem$lifespan, na.rm= TRUE, col='lightblue', main='distribution of lifespan', xlab='lifespan')
plot(epidem$clone[1:374], type='h')
boxplot(epidem$spores_tot, epidem$clutches, epidem$block, ylim=c(0, 15),
     col= 'chocolate', notch = T, outline= F, main='epidemiological data')
boxplot(epidem$spores_tot, epidem$clutches, epidem$block, ylim=c(0, 20), 
        col= 1:3, notch = T, outline=F, main='BOXPLOT', xlab='data', labels= c('EP', 'EC', 'EB'))
legend('topright', legend=c('EP', 'EC', 'EB'), col=1:3, pch=15)
read.table('https://raw.githubusercontent.com/HackBio-Internship/public_datasets/main/R/datasets/microbial_growth_data')
micgrowth<-read.table('https://raw.githubusercontent.com/HackBio-Internship/public_datasets/main/R/datasets/microbial_growth_data')
View(micgrowth)
plot(epidem$host_time_point, epidem$clutches, col= factor(epidem$treatment), pch=15, main='hosttime vs clutches', 
     xlab='host time', ylab='çlutches', xlim=c(1, 6), ylim=c(1, 10))
plot(epidem$host_time_point, epidem$clutches, col= factor(epidem$treatment), pch=15, main='hosttime vs clutches', xlab='host time', ylab='çlutches', xlim=c(1, 6), ylim=c(1, 10))
print(epidem)
levels(epidem$treatment)<-c("A","B", "C")
legend= levels(epidem$treatment)
legend('topright', legend = levels(epidem$treatment))
legend('topright', legend = levels(epidem$treatment), col=1:3, pch=15)
par(mfrow=c(3,4))
par(mfrow=c(1,1))
table(epidem$treatment)
item<-unique(epidem$treatment)
itemcount<-as.vector(table(epidem$treatment))
pie(x=itemcount, labels=item, radius = 0.5)
pie(x=itemcount, labels=item, radius = 0.5, edge=F, border= 'red')
#Insights
scatter plot main"hosttime vs clutches" when paired together showed that there was more of response to treatment A and less that responded to treatment B,average number responded to treatment"C'"
Install.packages('ggplot2')
